### ISSUE TITLE
Ajax-bypass completely breaks on browsers without window.fetch

### ISSUE THREAD

**Issue by cekrem** [sanfrancesco/prerendercloud-ajaxmonkeypatch#2]
This crashes on browsers without window.fetch. The patching is naively placed inside a try/catch, but that only catches errors while _defining_ the functions relying on fetch, not actually calling them.

**Comment by jotto** [comment]
@cekrem, thank you for taking the time to write. Do you have an example URL where this broke? Is it breaking because there's a polyfill defining window.fetch after this ajax-bypass monkeypatch?

**Comment by jotto** [comment]
@cekrem this change is now live on prerender.cloud - let me know if it solves your issue (or give me a URL where it's broken and I'll debug and fix)

**Comment by cekrem** [comment]
Thank you for fixing, but as far as I can tell the dist files are still the same? No if (window.fetch) query there? Or am I missing something?

**Comment by jotto** [comment]
The minifier makes it hard to see. It's using the comma operator https://javascriptweblog.wordpress.com/2011/04/04/the-javascript-comma-operator/

Here's a screenshot after using prettier to format it and: `git diff --no-index --color --color-words`

![image](https://cloud.githubusercontent.com/assets/16573/25862789/27cdf2e8-349e-11e7-9b35-9b1f440d2634.png)

**Comment by cekrem** [comment]
Just edited this post – I got it, thanks.

It still breaks, but that must be due to some lag in prerender.cloud not using latest commit. Thanks for your patient explanation!

**Comment by jotto** [comment]
![image](https://cloud.githubusercontent.com/assets/16573/25884463/6e3e5808-3507-11e7-8bb7-8e81ca962d0c.png)

**Comment by jotto** [comment]
@cekrem I'd love to get to the bottom of this, comment here, or email me a link to a URL where it's broken. support@prerender.cloud

**Comment by cekrem** [comment]
https://www.bfo.no/kontakt-oss

this breaks because it seems to use an old version of this monkey-patch. In addition, I added some headers to disable the patch completely – they are disregarded :/

![screen shot 2017-05-10 at 08 26 32](https://cloud.githubusercontent.com/assets/5259077/25885743/8032c5be-355a-11e7-8b3c-92aafb48674b.png)

**Comment by jotto** [comment]
> seems to use an old version of this monkey-patch

I just double checked that the new bypass code is in fact deployed, and I am also using the `Prerender-Disable-Ajax-Bypass` in several places successfully.

Can you double check that you don't have some cache somewhere that needs to be deleted?

**Comment by cekrem** [comment]
![screen shot 2017-05-10 at 08 46 33](https://cloud.githubusercontent.com/assets/5259077/25886300/3f294608-355d-11e7-80fb-370c3ee286bf.png)

This page was created just now, and viewing it in vim shows the old code. There might be cache involved in the link I sent you (although it shouldn't), but in the raw html there is none.

**Comment by cekrem** [comment]
`
(function (a) {
  // Ajax-Bypass monkeypatch injected by https://www.prerender.cloud to make this JS app isomorphic
  // see https://github.com/sanfrancesco/prerendercloud-ajaxmonkeypatch
  try {
    String.prototype.startsWith||(String.prototype.startsWith=function(d,e){return e=e||0,this.substr(e,d.length)===d});var b=a.XMLHttpRequest.prototype.open;a.XMLHttpRequest.prototype.open=function(){var d=arguments[1],e=b.apply(this,arguments);return(d.startsWith(a.location.origin)||d.startsWith('/'))&&this.setRequestHeader('x-prerendered','true'),e};var c=a.fetch;a.fetch=function(d,e){return d&&d.headers?(d&&d.url&&(d.url.startsWith('/')||d.url.startsWith(a.location.origin))&&d.headers.set('x-prerendered',!0),c(d,e||d)):(d&&(d.startsWith('/')||d.startsWith(a.location.origin))&&(e=e||{},e.headers=e.headers||{},e.headers['x-prerendered']='true'),c(d,e))}
  } catch (error) {
    console.error('prerender.cloud ajax bypass monkeypatch parse failure', error);
  }

})(window, '')
`

Here is the code present in the newly prerendered index.html (bfo.no/kontakt-oss/)

**Comment by jotto** [comment]
> There might be cache involved in the link I sent you (although it shouldn't)

* @cekrem can you double check that your webserver that's serving prerendered content is not returning old/cached data?
* And, what kind of configuration for prerender.cloud are you using?
